# This schema defines what will be extracted from the input text.
# It is loaded in schema.py and converted to a pydantic model.
# When processing the documents, the pydantic model is used to validate the
# output of the LLM. Note: use double quotations, for example
# Literatal["positive", ...], not Literal['positive', ...]

topic:
  type: Literal["price", "quality", "shipping", "other"]
  description: The topic of the input text (assuming a single topic per text)

sentiment:
  type: Literal["positive", "negative", "neutral"]
  description: The sentiment of the input text

keywords:
  type: list[str]
  description: At most 3 key phrases of the input text
